# Generated by Django 2.0.7 on 2021-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('industry', models.TextField()),
                ('size', models.TextField()),
                ('location', models.TextField()),
                ('website_url', models.TextField()),
            ],
        ),
    ]
