# Generated by Django 3.2.4 on 2021-06-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0009_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_page/default_company_logo.png', upload_to=''),
        ),
    ]
