# Generated by Django 3.2.4 on 2021-06-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='default_company_logo.png', upload_to=''),
        ),
    ]
