# Generated by Django 3.2.4 on 2021-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210608_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Partner', 'Partner'), ('Student', 'Student'), ('Instructor', 'Instructor')], default='---Select Role---', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
