# Generated by Django 3.2.4 on 2021-06-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='companies',
            new_name='company',
        ),
    ]
