# Generated by Django 3.2.4 on 2021-06-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210609_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
