# Generated by Django 3.2.4 on 2021-06-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_role',
            field=models.CharField(choices=[('admin', 'admin'), ('admin_pending_approval', 'admin_pending_approval'), ('member', 'member')], default='member', max_length=100),
        ),
    ]
