# Generated by Django 3.2.4 on 2021-06-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210627_1654'),
        ('users', '0006_user_role'),
    ]

    operations = [
    ]
