# Generated by Django 3.2.4 on 2021-06-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_company_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member'), ('pending_member', 'pending_member')], default='member', max_length=100),
        ),
    ]
