# Generated by Django 3.2.5 on 2021-07-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_mobile_phone'),
        ('users', '0007_alter_user_company_role'),
    ]

    operations = [
    ]
