# Generated by Django 3.2.4 on 2021-06-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='Nothing to be described'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('air', 'air'), ('marine', 'marine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.TextField(default='Toronto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.TextField(default='0-5'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.TextField(default='https://google.com'),
        ),
    ]
