# Generated by Django 3.2.5 on 2021-07-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tag',
            field=models.CharField(choices=[('primary', 'Pitch Decks'), ('secondary', 'Financial Decks'), ('success', 'MC'), ('info', 'Founding Team'), ('warning', 'other')], default='MC', max_length=100),
            preserve_default=False,
        ),
    ]
