# Generated by Django 3.2.4 on 2021-06-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0003_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('0-3', '0-3'), ('4-6', '4-6'), ('6-10', '6-10'), ('10-20', '10-20'), ('20+', '20+')], default='0-3', max_length=20),
        ),
    ]
