# Generated by Django 3.2.4 on 2021-06-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0006_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='https://www.google.com/search?q=company+default+logo&rlz=1C5CHFA_enCA698CA698&sxsrf=ALeKk02QodXYZCnKDEmzOk8WObALI-SLDQ:1622936775267&tbm=isch&source=iu&ictx=1&fir=dRTb9wjDif4u3M%252CYQigbWHisaAQJM%252C_&vet=1&usg=AI4_-kRYiAyav1BMbELM2Uqlsw_ggrbWIQ&sa=X&ved=2ahUKEwjQtO3P1oHxAhXjEVkFHUJJAOgQ9QF6BAgTEAE&biw=1442&bih=946#imgrc=dRTb9wjDif4u3M', upload_to=''),
        ),
    ]
