# Generated by Django 3.2.4 on 2021-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0014_auto_20210606_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('0-3 employees', '0-3'), ('4-6 employees', '4-6'), ('6-10 employees', '6-10'), ('10-20 employees', '10-20'), ('20+ employees', '20+')], default='0-3', max_length=20),
        ),
    ]
