# Generated by Django 3.2.4 on 2021-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0017_alter_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[(0, 'Self-employed'), (1, 'Public company'), (2, 'Government agency'), (3, 'Nonprofit'), (4, 'Sole proprietorship'), (5, 'Privately-held'), (6, 'Partnership')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='verify',
            field=models.BooleanField(default=False, help_text='I verify that I am an authorized representative of this organization and have the right to act on its behalf in the creation and management of this page. The organization and I agree to the additional terms for Pages.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, help_text='URL should start with https://', null=True),
        ),
    ]
