# Generated by Django 3.2.4 on 2021-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0018_auto_20210608_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('a', 'Self-employed'), ('b', 'Public company'), ('c', 'Government agency'), ('d', 'Nonprofit'), ('e', 'Sole proprietorship'), ('f', 'Privately-held'), ('g', 'Partnership')], default='a', max_length=20),
        ),
    ]
