# Generated by Django 3.2.4 on 2021-06-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0019_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
