# Generated by Django 3.2.4 on 2021-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0020_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='default_company_logo.png', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('0-3', '0-3 employees'), ('4-6', '4-6 employees'), ('6-10', '6-10 employees'), ('10-20', '10-20 employees'), ('20+', '20+ employees')], default='0-3', max_length=20),
        ),
    ]
