# Generated by Django 3.2.4 on 2021-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0021_auto_20210611_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='verify',
            field=models.BooleanField(default=False, help_text='I verify that I am an authorized representative of this organization and have the right to act on its behalf in the creation and management of this page. '),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
