# Generated by Django 3.2.4 on 2021-06-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0022_auto_20210626_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='img/default_company_logo.png', null=True, upload_to='img'),
        ),
    ]
