# Generated by Django 3.2.4 on 2021-07-01 01:17

import company_page.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0023_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=company_page.models.get_upload_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_page.company')),
            ],
        ),
    ]
