# Generated by Django 3.2.4 on 2021-07-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0024_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='file', max_length=100),
            preserve_default=False,
        ),
    ]
