# Generated by Django 3.2.4 on 2021-07-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0027_rename_date_posted_file_data_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.CharField(blank=True, choices=[('pitch_decks', 'Pitch Decks'), ('financial_decks', 'Financial Decks'), ('MC', 'MC'), ('founding_team', 'Founding Team'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
