# Generated by Django 3.2.4 on 2021-07-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0028_auto_20210630_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='logo/default_company_logo.png', null=True, upload_to='logo'),
        ),
    ]
