# Generated by Django 3.2.4 on 2021-07-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0030_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verify',
            field=models.BooleanField(default=False, help_text='I understand all information uploaded will be made public to the platform users. '),
        ),
        migrations.AddField(
            model_name='photo',
            name='verify',
            field=models.BooleanField(default=False, help_text='I understand all information uploaded will be made public to the platform users. '),
        ),
    ]
