# Generated by Django 3.2.5 on 2021-07-14 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificationsForum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationforum',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationforum',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notificationforum',
            name='emailed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificationforum',
            name='action_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_action_object_forum', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notificationforum',
            name='actor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor_forum', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notificationforum',
            name='public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='notificationforum',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_target_forum', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notificationforum',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationforum',
            name='unread',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterIndexTogether(
            name='notificationforum',
            index_together={('recipient', 'unread')},
        ),
    ]
