# Generated by Django 3.2.4 on 2021-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_page', '0004_auto_20210605_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(default='https://www.google.com/search?q=company+default+logo&rlz=1C5CHFA_enCA698CA698&sxsrf=ALeKk02QodXYZCnKDEmzOk8WObALI-SLDQ:1622936775267&tbm=isch&source=iu&ictx=1&fir=dRTb9wjDif4u3M%252CYQigbWHisaAQJM%252C_&vet=1&usg=AI4_-kRYiAyav1BMbELM2Uqlsw_ggrbWIQ&sa=X&ved=2ahUKEwjQtO3P1oHxAhXjEVkFHUJJAOgQ9QF6BAgTEAE&biw=1442&bih=946#imgrc=dRTb9wjDif4u3M'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default='Toronto', max_length=100),
        ),
    ]
