# Generated by Django 3.2.4 on 2021-06-25 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='coursename')),
                ('study_time', models.IntegerField(default=0, verbose_name='study time')),
                ('study_num', models.IntegerField(default=0, verbose_name='study num')),
                ('star_num', models.IntegerField(default=0, verbose_name='star')),
                ('click_num', models.IntegerField(default=0, verbose_name='clicks')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'coursename',
                'verbose_name_plural': 'coursename',
            },
        ),
        migrations.CreateModel(
            name='LessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='chaptername')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('courseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo', verbose_name='course info')),
            ],
            options={
                'verbose_name': 'lession_name',
                'verbose_name_plural': 'lession_name',
            },
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='videoname')),
                ('study_time', models.IntegerField(default=0, verbose_name='study_time')),
                ('url', models.URLField(default='https://www.utoronto.ca/', verbose_name='movie link')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('lessoninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessioninfo', verbose_name='lessoninfo')),
            ],
            options={
                'verbose_name': 'video_name',
                'verbose_name_plural': 'video_name',
            },
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='resourcename')),
                ('downloads', models.FileField(max_length=200, upload_to='source/', verbose_name='downloadpath')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resource',
            },
        ),
    ]
