# Generated by Django 3.2.4 on 2021-06-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceinfo',
            name='course_info',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='lessoninfo',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='click_num',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='star_num',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='study_num',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='study_time',
        ),
        migrations.DeleteModel(
            name='LessionInfo',
        ),
        migrations.DeleteModel(
            name='SourceInfo',
        ),
        migrations.DeleteModel(
            name='VideoInfo',
        ),
    ]
