# Generated by Django 3.2.4 on 2021-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210625_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Course Name'),
        ),
    ]
