# Generated by Django 3.2.4 on 2021-06-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210625_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
