# Generated by Django 3.2.4 on 2021-07-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_book_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='course',
        ),
        migrations.CreateModel(
            name='BookCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo')),
            ],
        ),
    ]
