# Generated by Django 3.2.4 on 2021-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
