# Generated by Django 3.2.4 on 2021-06-25 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='chaptername')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'lession_name',
                'verbose_name_plural': 'lession_name',
            },
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='coursename'),
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='videoname')),
                ('study_time', models.IntegerField(default=0, verbose_name='study_time')),
                ('url', models.URLField(default='https://www.utoronto.ca/', verbose_name='movie link')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('lessoninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessioninfo', verbose_name='lessoninfo')),
            ],
            options={
                'verbose_name': 'video_name',
                'verbose_name_plural': 'video_name',
            },
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='resourcename')),
                ('downloads', models.FileField(max_length=200, upload_to='source/', verbose_name='downloadpath')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resource',
            },
        ),
        migrations.AddField(
            model_name='lessioninfo',
            name='courseinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinfo', verbose_name='course info'),
        ),
    ]
