# Generated by Django 3.2.5 on 2021-07-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_mark_upload_uploadbookuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.mark')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.upload')),
            ],
        ),
    ]
