# Generated by Django 3.2.4 on 2021-06-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210625_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessioninfo',
            name='add_time',
        ),
    ]
