# Generated by Django 3.2.5 on 2021-07-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_uploadmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='mark',
        ),
    ]
