# Generated by Django 3.2.5 on 2021-07-25 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_remove_upload_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmark',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(max_length=5),
        ),
    ]
