# Generated by Django 3.2.4 on 2021-06-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lessioninfo_add_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessionInfo',
            new_name='LessonInfo',
        ),
    ]
