# Generated by Django 3.2.5 on 2021-07-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210725_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmark',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.book'),
            preserve_default=False,
        ),
    ]
