# Generated by Django 3.2.5 on 2021-07-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_uploadmark_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmark',
            name='user',
        ),
    ]
