# Generated by Django 3.2.5 on 2021-07-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_upload_uploadbookuser'),
        ('courses', '0011_remove_uploadmark_user'),
    ]

    operations = [
    ]
